name: Count Number of Words

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.mdx'

jobs:
  count_no_words:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install actions-toolkit

      - name: Extract changed files, with .mdx extension
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: json

      - name: Check Number of Words
        run: |
          python .github/scripts/count_no_words.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.added_modified }}
          REMOVED_FILES: ${{ steps.changed-files.outputs.removed }}
